# For more information: https://laravel.com/docs/sail
services:
    laravel.test:
        image: 'jeffersonlab/jlab-sail:8.1.0'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - oracle
    oracle:
        image: 'gvenzl/oracle-xe:18'
        hostname: oracle
        ports:
            - '${FORWARD_ORA_PORT:-1521}:1521'
        environment:
            ORACLE_PASSWORD: '${ORACLE_PASSWORD}'
            APP_USER: '${APP_USER}'
            APP_USER_PASSWORD: '${APP_USER_PASSWORD}'
            DB_PASSWORD: '${DB_PASSWORD}'
        volumes:
            # Keeps persistent oracle data in project run directory
            - './run/var/oracle/oradata:/opt/oracle/oradata'
            #  *.sql, *.sql.gz, *.sql.zip or *.sh scripts to perform additional initialization of the database
            #  that are only run the first time the database is initialized.
            - './run/var/oracle/initdb:/container-entrypoint-initdb.d'
            # *.sql, *.sql.gz, *.sql.zip or *.sh scripts to perform additional action after the database
            # running has been started
            - './run/var/oracle/startdb:/container-entrypoint-startdb.d'
        networks:
            - sail
networks:
    sail:
        driver: bridge

